### ISSUE TITLE
Gom dữ liệu được tạo ra vào thư mục riêng

### ISSUE THREAD

**Issue by virusvn** [hailoc12/docbao#2]
Các file được tạo ra bởi chương trình nên được gom vào thư mục riêng, ví dụ: `client\data`:

`hot_keyword.json`
`keyword_dict.json`
`uncategorized_keyword.txt`
`article_data.json`
`article.dat`
`blacklist.dat`
`log_data.json`

Và cho vào `.gitignore` cái thư mục này luôn, làm vậy cho mã nguồn nhìn gọn bớt :)
Hoặc tạo cái file config, để chỉ nơi chứa từng file, vì có thể triển khai cả client và server trên cùng 1 máy chủ, nên sẽ cập nhật trực tiếp server luôn, không cần phải dùng rclone.

**Comment by hailoc12** [comment]
Rất cám ơn bạn đã nhận xét, mình sẽ fix vấn đề này
