### ISSUE TITLE
Tim hieu cach contribute cac yaml moi

### ISSUE THREAD

**Issue by chaunnt** [hailoc12/docbao#21]
mình thấy project rất hay và muốn làm 1 số resource yaml khác cho phục vụ nhu cầu cá nhân, đồng thời contribute luôn.
Nhưng khi đọc cái yaml hiện tại thì thấy khá là rối @@ nhìn hơi khó hiểu.
Không biết owner có thể share 1 chút về cách làm không ?, sample nói nhanh vài step là được rồi :) 
Mình cũng là dev

**Comment by hailoc12** [comment]
Cám ơn bạn đã quan tâm, mình đã bổ sung tài liệu hướng dẫn cấu hình trang báo mới vào folder /docs. Bạn tham khảo nhé
