### ISSUE TITLE
Phân phối crawler dữ liệu tin tức qua RSS

### ISSUE THREAD

**Issue by ancs21** [hailoc12/docbao#3]
### **Idea**
Mỗi website tin tức đều có RSS cho từng danh mục
Ví dụ trang `nld.com.vn ` có https://nld.com.vn/thoi-su.rss
Link RSS chứa thông tin các `item` mỗi `item` trình bày như bên dưới
```
<item>
<title>
<![CDATA[
Điều tra vụ vay người dân hàng trăm tỉ đồng không có khả năng chi trả
]]>
</title>
<link>
<![CDATA[
https://nld.com.vn/thoi-su/dieu-tra-vu-vay-nguoi-dan-hang-tram-ti-dong-khong-co-kha-nang-chi-tra-20180907100003166.htm
]]>
</link>
<guid isPermaLink="false">
<![CDATA[
https://nld.com.vn/thoi-su/dieu-tra-vu-vay-nguoi-dan-hang-tram-ti-dong-khong-co-kha-nang-chi-tra-20180907100003166.htm
]]>
</guid>
<description>
<![CDATA[
<img src="https://nld.mediacdn.vn/zoom/130_200/2018/9/7/anh-15362890843522110867625.jpg" alt="Điều tra vụ vay người d&#226;n h&#224;ng trăm tỉ đồng kh&#244;ng c&#243; khả năng chi trả" title="Điều tra vụ vay người d&#226;n h&#224;ng trăm tỉ đồng kh&#244;ng c&#243; khả năng chi trả" width="130px" height="200px" />(NLĐO)- Cơ quan chức năng Quảng Trị đang điều tra, l&#224;m r&#245; tin b&#225;o một người phụ nữ vay khoảng 400 tỉ đồng của h&#224;ng chục người d&#226;n nhưng kh&#244;ng c&#243; khả năng chi trả.
]]>
</description>
<pubDate>9/7/2018 9:59:00 AM</pubDate>
</item>
```
### **Cách thực hiện**
**- Bước 1**. Mỗi trang web tin tức, cralwer tất cả RSS cho danh mục cụ thể
**- Bước 2**. Mỗi link RSS sẽ được thực hiện crawler tuần tự để lấy thông tin cần
**- Bước 3**. Thực hiện song song tất cả website tin tức mỗi 10 phút

__Tips__:
- Tránh block IP do request nhiều lần -> Thay đổi user agent trình duyệt + sử dụng proxy để fake IP
- Tránh trùng dữ liệu và crawler -> Kiểm tra thời gian item đầu tiên của mỗi link RSS, nếu nó khác lần cuối thực hiện, sẽ tiến lấy dữ liệu từ thời gian đó lên.

### **Code**
Đang thực hiện

**Comment by hailoc12** [comment]
Cám ơn bạn, tính năng này có thể phát triển dưới dạng một chiến lược quét (rss hoặc quét a tag...giống như scrapy có hỗ trợ), tuy nhiên trong tương lai gần chắc đây sẽ chưa phải là hướng ưu tiên :d
