### ISSUE TITLE
Tính năng autocomplate hoạt động chậm khi dữ liệu quét lớn

### ISSUE THREAD

**Issue by hailoc12** [hailoc12/docbao#5]
Ô tìm kiếm trên trang http://theodoibaochi.com/ hoạt động chậm do autocomplete được kích hoạt sau mỗi kí tự gõ, nên tạo ra một khoảng trễ nhất định (vd. 0.5s mới search)

**Comment by bboyadao** [comment]
bỏ thuộc tính onkeyup. hãy dùng oncomplete. để gọi đến js
