### ISSUE TITLE
Lỗi export dữ liệu bằng pickle ở backend khi số trường vượt quá 15.000

### ISSUE THREAD

**Issue by hailoc12** [hailoc12/docbao#6]
Lỗi này do write file ở chế độ wb, do đó nếu gặp lỗi thì xóa đè file dữ liệu đã có. 

Giải pháp tạm thời: ghi ra một file temp, nếu không gặp lỗi thì thay thế file chính thức

Giải pháp lâu dài: thay thế cơ chế pickle bằng sqlite, viết một class database riêng để xử lý vấn đề này

**Comment by bboyadao** [comment]
why pickle ?
