### ISSUE TITLE
Xây dựng mô hình quét phân tán để dễ scale

### ISSUE THREAD

**Issue by hailoc12** [hailoc12/docbao#7]
Góp ý của anh Nguyễn Bá Hòa: 

- Về mặt triển khai thì nếu đưa lên hệ thống k8s được thì rất tốt, vì quản lý tốt, scale tốt, nếu dự kiến dự án lớn và lâu dìa thì thật sự rất nên áp dụng k8s. chỉ cần 1 master và 1 vài worker là được. khi nào có bạn nào cho mượn vps thì chỉ cần join vào là xong. triển khai hai môi trường cũng dễ, dev và test hoặc các môi trường khác trong nháy mắt nếu cấu hình tốt
- - Về phần crawler thì dù làm bằng gì cũng phải được xử lý phân tán, vì crawler là tác vụ mất khá nhiều thời gian và liên tục, nếu được thì nên cấu trúc thành các worker để crawler, sử dụng redis làm queue cho worker chạy. sau cần scale out ra thì thêm worker là xong

**Comment by bboyadao** [comment]
selenium-grid
